<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="22674414-adf2-4147-92da-5afbf0caee65" name="Sergey Zwezdin@OOGWAY 2011-05-21 10:36:41" runUser="OOGWAY\Sergey Zwezdin" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="c8503907-1843-48ad-a13a-1bbb05c0eec0">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Sergey Zwezdin_OOGWAY 2011-05-21 10_36_41">
      <DeploymentItem filename="D:\OpenSource\Monads\Monads\bin\Debug\Monads.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2011-05-21T10:36:41.0513439+06:00" queuing="2011-05-21T10:36:41.1553498+06:00" start="2011-05-21T10:36:41.1933520+06:00" finish="2011-05-21T10:36:41.5933749+06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TryWithOnObjectWithException" storage="d:\opensource\monads\monads.tests\bin\debug\monads.tests.dll" id="6c2d098c-4a90-181f-fd67-ac956c9fa4a4">
      <Execution id="dd854176-5889-4b1d-8b90-d0518b0eb440" />
      <TestMethod codeBase="D:/OpenSource/Monads/Monads.Tests/bin/Debug/Monads.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Monads.Tests.MaybeTests, Monads.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TryWithOnObjectWithException" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="6c2d098c-4a90-181f-fd67-ac956c9fa4a4" executionId="dd854176-5889-4b1d-8b90-d0518b0eb440" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="dd854176-5889-4b1d-8b90-d0518b0eb440" testId="6c2d098c-4a90-181f-fd67-ac956c9fa4a4" testName="TryWithOnObjectWithException" computerName="OOGWAY" duration="00:00:00.0508931" startTime="2011-05-21T10:36:41.1983523+06:00" endTime="2011-05-21T10:36:41.5473722+06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="dd854176-5889-4b1d-8b90-d0518b0eb440">
      <Output>
        <ErrorInfo>
          <Message>Assert.AreEqual failed. Expected:&lt;{ Property1 =  }&gt;. Actual:&lt;(null)&gt;. </Message>
          <StackTrace>   в Monads.Tests.MaybeTests.TryWithOnObjectWithException() в D:\OpenSource\Monads\Monads.Tests\MaybeTests.cs:строка 238
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>